In [1]:
import open3d as o3d
import numpy as np
import pythreejs as p3
from IPython.display import display

In [2]:
import os
import sys
# 获取当前Notebook所在目录
current_dir = os.path.dirname(os.path.abspath('__file__'))

# 构造自建库路径
lib_path = os.path.join(current_dir, '../../utils_lee')
# 将自建库路径添加到系统路径中
sys.path.append(lib_path)

# from image_utils import ImageUtils
# from file_utils import FileUtils
from point_cloud_utils import PointCloudUtils

In [3]:
PointCloudUtils.render_point_cloud_with_axes(file_path="./artifact19.ply", point_size=0.0000001, canvas_dimensions=(900, 400), show_light=True)

/opt/anaconda3/envs/py312for3D/lib/python3.12/site-packages/pythreejs/traits.py:257: UserWarning: 64-bit data types not supported for WebGL data, casting to 32-bit.
  warnings.warn('64-bit data types not supported for WebGL '


Renderer(camera=PerspectiveCamera(aspect=2.25, fov=75.0, position=(0.0, 0.0, 3.0), projectionMatrix=(1.0, 0.0,…

# 〇. 点云文件地址

In [6]:
ply1_path = "./artifact19.ply"
ply2_path = "./bumpy_plane_test_4.ply"
off_path = "./bookshelf_0574.off"

# 一. 点云可视化
`o3d.visualization.draw_geometries` 

## 基本用法

```python
o3d.visualization.draw_geometries([geometry0, geometry1, ...], window_name='Open3D', width=800, height=600, point_show_normal=False, mesh_show_wireframe=False, mesh_show_back_face=False)
```

## 参数说明
| 参数名称 | 类型 | 描述 | 默认值 |
| :--: | :--: | :--: | :--: |
| geometries | list of `o3d.geometry.Geometry3D` | 包含要可视化的3D几何体的列表。可以是点云、网格等。 | 无（必须提供） |
| window_name | str | 显示窗口的名称。 | 'Open3D' |
| width | int | 窗口的宽度（以像素为单位）。 | 800 |
| height | int | 窗口的高度（以像素为单位）。 | 600 |
| point_show_normal | bool | 如果为True，则在点云中显示每个点的法线。 | False |
| mesh_show_wireframe | bool | 如果为True，则在网格上绘制线框。 | False |
| mesh_show_back_face | bool | 如果为True，则渲染网格的背面。 | False |

In [18]:
import open3d as o3d

# 读取PLY文件
ply_file = ply1_path
point_cloud = o3d.io.read_point_cloud(ply_file)

# 打印点云数据
print(point_cloud)
# 可视化点云
o3d.visualization.draw_geometries([point_cloud])

# 保存可见表面点云为ply文件
# o3d.io.write_point_cloud("visible_surface.ply", point_cloud)

PointCloud with 187114 points.


In [17]:
import open3d as o3d

# 创建一个点云
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector([[0, 0, 0], [1, 0, 0], [0, 1, 0]])

# 创建 Visualizer
vis = o3d.visualization.Visualizer()
vis.create_window()

# 添加点云到 Visualizer
vis.add_geometry(pcd)

# 获取相机参数
ctr = vis.get_view_control()
param = ctr.convert_to_pinhole_camera_parameters()

# 设置相机内参（例如，焦距、主点等）
param.intrinsic.set_intrinsics(width=800, height=600, fx=400, fy=400, cx=400, cy=300)

# 设置相机外参（例如，相机的位置和朝向）
param.extrinsic = o3d.core.Tensor([[1, 0, 0, 0], 
                                   [0, 1, 0, 0], 
                                   [0, 0, 1, -3], 
                                   [0, 0, 0, 1]])

# 应用新的相机参数
ctr.convert_from_pinhole_camera_parameters(param)

# 运行可视化
vis.run()

# 关闭窗口
vis.destroy_window()


TypeError: (): incompatible function arguments. The following argument types are supported:
    1. (self: open3d.cpu.pybind.camera.PinholeCameraParameters, arg0: numpy.ndarray[numpy.float64[4, 4]]) -> None

Invoked with: PinholeCameraParameters class.
Access its data via intrinsic and extrinsic., [[1 0 0 0],
 [0 1 0 0],
 [0 0 1 -3],
 [0 0 0 1]]
Tensor[shape={4, 4}, stride={4, 1}, Int64, CPU:0, 0x12a6f1710]